# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CreateCircleSector
                                 A QGIS plugin
 Create polygon defined by center, radius and two bearings
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-12-09
        copyright            : (C) 2018 by Paweł Strzelwicz
        email                : @
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CreateCircleSector class from file CreateCircleSector.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .create_circ_sector import CreateCircleSector
    return CreateCircleSector(iface)
